#!/bin/bash
IFS=$'\n' read -r -d '' -a ricelist < <( ls -1 ./Rices/ && printf '\0')
i=0
echo "Available Rices (${#ricelist[@]}) ==================="
for ricename in ${ricelist[@]}
do
    echo "  $i) $ricename"
    i=$(($i+1))
done
echo "======================================="
read -p "Enter theme index (0-$((${#ricelist[@]}-1))) : " themeidx


echo "Checking for shared rice scripts"
if [ ! -d ~/.shared-rice-scripts ]; then
    echo "Shared scripts not found"
    echo "Copying..."
    cp -f -r ./Rices/.shared-rice-scripts ~
else 
    echo "Updating scripts"
    cp -f -r ./Rices/.shared-rice-scripts ~
fi
echo "Finished copying"

if [ $themeidx -gt $((${#ricelist[@]}-1)) ]; then
    echo "Invalid theme index"
elif [ $themeidx -lt 0 ]; then
    echo "Invalid theme index"
else
    themename=${ricelist[$themeidx]}
    if [ $themename == $(cat ~/.current_rice_theme) ]; then
        echo "Reloading $themename"
    else
        echo "Switching to $themename"
    fi

    touch ~/.current_rice_theme
    echo "$themename" > ~/.current_rice_theme

    IFS=$'\n' read -r -d '' -a folderlist < <( ls -1 -A ./Rices/$themename/ && printf '\0')
    j=0
    for foldername in ${folderlist[@]}
    do
        echo "  $j> Copying ./Rices/$themename/$foldername to ~"
        cp -f -r ./Rices/$themename/$foldername ~
        j=$(($j+1))
    done    
    echo "Successfully switched to $themename"

    pkill waybar
    waybar > /dev/null 2>&1 & 
fi


